/**
 * إنشاء القائمة الجانبية (Sidebar).
 * * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // هذا هو اسم القائمة التي نستخدمها في docusaurus.config.js
  tutorialSidebar: [
    
    // 1. صفحة الترحيب (عادة تكون ملف intro.md في مجلد docs)
    'intro',

    // 2. القسم الأول: البداية والإعداد
    {
      type: 'category',
      label: '🚀 1. البداية والتهيئة',
      items: [
        // سيقوم بقراءة كل الملفات الموجودة داخل مجلد docs/01-getting-started
        {type: 'autogenerated', dirName: '01-getting-started'},
      ],
      collapsible: true,
      collapsed: false, // اجعل هذا القسم مفتوحاً افتراضياً
    },

    // 3. القسم الثاني: أساسيات البرمجة بلغة C++
    {
      type: 'category',
      label: '💻 2. أساسيات برمجة الأردوينو',
      items: [
        // docs/02-programming-basics
        {type: 'autogenerated', dirName: '02-programming-basics'},
      ],
      collapsible: true,
      collapsed: true,
    },

    // 4. القسم الثالث: التعامل مع المدخلات والمخرجات
    {
      type: 'category',
      label: '🔌 3. الإلكترونيات والدوائر',
      items: [
        // docs/03-electronics
        {type: 'autogenerated', dirName: '03-electronics'},
      ],
      collapsible: true,
      collapsed: true,
    },

    // 5. القسم الرابع: الحساسات والموديولات
    {
      type: 'category',
      label: '🌡️ 4. الحساسات والموديولات',
      items: [
        // docs/04-sensors
        {type: 'autogenerated', dirName: '04-sensors'},
      ],
      collapsible: true,
      collapsed: true,
    },

    // 6. القسم الخامس: مشاريع متكاملة
    {
      type: 'category',
      label: '🤖 5. مشاريع وتطبيقات عملية',
      items: [
        // docs/05-projects
        {type: 'autogenerated', dirName: '05-projects'},
      ],
      collapsible: true,
      collapsed: true,
    },
  ],
};

module.exports = sidebars;